models/Routers.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%routers}}".
 *
 * @property int $id
 * @property string $sap_id
 * @property string $hostname
 * @property string $loopback
 * @property string $mac_address
 * @property string $created_at
 * @property string $updated_at
 * @property int $created_by
 * @property int $updated_by
 */
class Routers extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%routers}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['sap_id', 'hostname', 'loopback', 'mac_address', /*'created_at', 'updated_at', 'created_by', 'updated_by'*/], 'required'],
            [['created_at', 'updated_at', 'deleted', 'deleted_at', 'deleted_by'], 'safe'],
            [['created_by', 'updated_by', 'deleted', 'deleted_by'], 'integer'],
            [['sap_id'], 'string', 'max' => 18],
            [['hostname'], 'string', 'max' => 14],
            [['hostname', 'loopback'], 'unique'],

            ['hostname', 'ip'], // IPv4 or IPv6 address
            // ['hostname', 'ip', 'ipv6' => false], // IPv4 address (IPv6 is disabled)
            // ['hostname', 'ip', 'subnet' => true], // requires a CIDR prefix (like 10.0.0.1/24) for the IP address
            // ['hostname', 'ip', 'subnet' => null], // CIDR prefix is optional
            // ['hostname', 'ip', 'subnet' => null, 'normalize' => true], // CIDR prefix is optional and will be added when missing
            // ['hostname', 'ip', 'ranges' => ['192.168.0.0/24']], // only IP addresses from the specified subnet are allowed
            // ['hostname', 'ip', 'ranges' => ['!192.168.0.0/24', 'any']], // any IP is allowed except IP in the specified subnet
            // ['hostname', 'ip', 'expandIPv6' => true], // expands IPv6 address to a full notation format
            
            [['loopback'], 'string', 'max' => 20],
            [['mac_address'], 'string', 'max' => 17],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'sap_id' => 'SAP ID',
            'hostname' => 'Hostname',
            'loopback' => 'Loopback',
            'mac_address' => 'Mac Address',
            'deleted' => 'Deleted',
            'deleted_at' => 'Deleted At',
            'deleted_by' => 'Deleted By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {

        if (parent::beforeSave($insert)) {
            if (!Yii::$app->user->isGuest && $this->isNewRecord) {
                $this->created_by = $this->updated_by = Yii::$app->user->identity->id;
            } elseif (!Yii::$app->user->isGuest && !$this->isNewRecord) {
                $this->updated_by = Yii::$app->user->identity->id;
            }

            if ($this->isNewRecord) {
                $this->created_at = $this->updated_at = date('Y-m-d H:i:s');
            } else {
                $this->created_at = date('Y-m-d H:i:s', strtotime($this->created_at));
                $this->updated_at = date('Y-m-d H:i:s');
            }
            return true;
        } else {
            return false;
        }
    }
}

controllers/RoutersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Routers;
use app\models\RoutersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RoutersController implements the CRUD actions for Routers model.
 */
class RoutersController extends Controller
{
    public $enableCsrfValidation = false;
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Routers models.
     * @return mixed
     */
    public function actionIndex($id = null)
    {
        // $this->enableCsrfValidation = false;
        $searchModel = new RoutersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = new Routers();


        if ($id) {
            $model = $this->findModel($id);
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'model' => $model,
            ]);
        } else {
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays a single Routers model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Routers model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    // public function actionCreate()
    // {
    //     $model = new Routers();

    //     if ($model->load(Yii::$app->request->post()) && $model->save()) {
    //         return $this->redirect(['view', 'id' => $model->id]);
    //     }

    //     return $this->render('create', [
    //         'model' => $model,
    //     ]);
    // }

    public function actionAjaxCreate()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $model = new Routers();

        if (!Yii::$app->request->isPost) {
            $res = [
                'status'=>'failed',
                'message'=>'Only post methond is allowed',
            ];
            return $this->asJson($res);
        }
        
        $model->load(Yii::$app->request->post());
        
        if ($model->validate()) {
            $model->save(false);
            $res = [
                'status'=>'success',
                'message'=>'Record created successfully',
            ];
            
            return $this->asJson($res);
        } else {
            $res = [
                'status'=>'failed',
                'message'=>'Validation failed.',
                'errors'=>$model->getErrors()
            ];
            return $this->asJson($res);
        }
    }


    /**
     * Updates an existing Routers model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    // public function actionUpdate($id)
    // {
    //     $model = $this->findModel($id);
        
    //     if ($model->load(Yii::$app->request->post()) && $model->save()) {
    //         return $this->redirect(['view', 'id' => $model->id]);
    //     }

    //     return $this->render('update', [
    //         'model' => $model,
    //     ]);
    // }

    public function actionAjaxUpdate($id)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        if (!Yii::$app->request->isPost) {
            $res = [
                'status'=>'failed',
                'message'=>'Only post methond is allowed',
            ];
            return $this->asJson($res);
        }

        $model = $this->findModelByID($id);
        
        if(!$model) {
            $res = [
                'status'=>'failed',
                'message'=>'Recored not found.',
            ];
            return $this->asJson($res);
        }
        
        $model->load(Yii::$app->request->post());
        
        if ($model->validate()) {
            $model->save(false);
            $res = [
                'status'=>'success',
                'message'=>'Record updated successfully',
            ];
            
            return $this->asJson($res);
        } else {
            $res = [
                'status'=>'failed',
                'message'=>'Validation failed.',
                'errors'=>$model->getErrors()
            ];
            return $this->asJson($res);
        }
        
        
    }

    /**
     * Deletes an existing Routers model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    // public function actionDelete($id)
    // {
    //     //$this->findModel($id)->delete();
    //     $model = $this->findModel($id);
    //     $model->deleted = 1;
    //     $model->deleted_by = 1; // Put here user id of user from session
    //     $model->deleted_at = date('Y-m-d H:i:s');
    //     $model->save();
    //     return $this->redirect(['index']);
    // }


    public function actionAjaxDelete($id)
    {
        //$this->findModel($id)->delete();
        $model = $this->findModel($id);
        //$model->deleted = ($model->deleted === 1 )? 0 : 1;
        $model->deleted = 1;
        $model->deleted_by = 1; // Put here user id of user from session
        $model->deleted_at = date('Y-m-d H:i:s');
        $model->save();
        $res = [
            'status'=>'success',
            'message'=>'Record deleted successfully',
        ];
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return $this->asJson($res);
        // return $this->redirect(['index']);
    }



    /**
     * Finds the Routers model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Routers the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Routers::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    protected function findModelByID($id)
    {   
        if (($model = Routers::findOne($id)) !== null) {
            return $model;
        }
        return null;
    }
}

views/routers/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Routers */
/* @var $form yii\widgets\ActiveForm */
?>

<h3 class="widget-title">
    <?php if (!$model->isNewRecord) : ?>
    <i class="ace-icon glyphicon glyphicon-edit"></i> Update <?php echo Html::encode($this->title); ?>
    <?php else : ?>
    <i class="ace-icon glyphicon glyphicon-plus"></i> Add <?php echo Html::encode($this->title); ?>
    <?php endif; ?>
</h3>
<hr/>
<div class="routers-form">
    <?php
    $form_action = ($model->isNewRecord) ? ['routers/ajax-create'] : ['routers/ajax-update', 'id'=>$model->id];
    ?>
    <?php $form = ActiveForm::begin(['action'=>$form_action, 'id'=>'form-routers']); ?>
    
    <?php echo $form->field($model, 'sap_id')->textInput(['maxlength' => true]); ?>

    <?php echo $form->field($model, 'hostname')->textInput(['maxlength' => true]); ?>

    <?php echo $form->field($model, 'loopback')->textInput(['maxlength' => true]); ?>

    <?php echo $form->field($model, 'mac_address')->textInput(['maxlength' => true]); ?>


    <div class="form-group">
        <?php echo Html::submitButton('Save', ['id'=>'save-btn', 'class' => 'btn btn-success']); ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

<script>
//  $(function(){
    // $( "form#form-routers" ).submit(function( event ) {
        // event.preventDefault();
        // const form = document.querySelector('form#form-routers');
        // const data = Object.fromEntries(new FormData(form).entries());
        // console.log(form);
        // console.log(data);
        // $.ajax({          
        //     type: 'POST',
        //     dataType: 'json',
        //     data: data,
        //     cache: false,
        //     url: '<?php echo Yii::$app->urlManager->createUrl(['routers/ajax-update', 'id' => $model->id]); ?>',
        //     success: function(response) {
        //     if(response.status == 'success') {
        //         alert(response.message);                                                
        //     }
        //         $.pjax.reload({container: '#" . $pjaxgridview_id . "'});
        //     }
        //     return false;
        // });
        // return false;
    // });
// });

// $(function() {
//     $(document).on("submit", "form#form-routers", function(event) {
//         event.preventDefault(); // stopping submitting
//         var data = $(this).serializeArray();
//         var url = $(this).attr('action');
//         $.ajax({
//             url: url,
//             type: 'post',
//             dataType: 'json',
//             data: data
//         })
//         .done(function(response) {
//             if (response.status == 'success') {
//                 alert("Wow you commented");
//                 $.pjax.reload({container: '#router'});
//             }
//         })
//         .fail(function() {
//             console.log("error");
//         });
    
//     });
// });
</script>

views/routers/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RoutersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="routers-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'sap_id') ?>

    <?= $form->field($model, 'hostname') ?>

    <?= $form->field($model, 'loopback') ?>

    <?= $form->field($model, 'mac_address') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/routers/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Routers */

$this->title = 'Create Routers';
$this->params['breadcrumbs'][] = ['label' => 'Routers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
	<div class="col-md-4">
	  	<div class="routers-create">
		    <h1><?= Html::encode($this->title) ?></h1>
		    <?= $this->render('_form', [
		        'model' => $model,
		    ]) ?>
		</div>
	</div>
	<div class="col-md-8">
	  One of three columns
	</div>
</div>

views/routers/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\RoutersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Routers';
$this->params['breadcrumbs'][] = $this->title;
$pjaxgridview_id = 'router';
?>

<?php Pjax::begin(['id' => $pjaxgridview_id, 'enablePushState' => false, 'clientOptions' => ['method' => 'POST']]); ?>
    
<div class="row">
    <div class="col-md-3">
        <?php //Pjax::begin(['id' => $pjaxgridview_id.'form', 'enablePushState' => false]); ?> 
        <?php echo $this->render('_form', ['model' => $model]); ?>
        <?php //Pjax::end(); ?>
    </div>
    <div class="col-md-9">    
        <div class="routers-index">
        <h1><?= Html::encode($this->title) ?> <?= Html::a('Create Routers', ['routers/index'], ['class' => 'btn btn-success']) ?></h1>
        
        <?php //Pjax::begin(); ?>
        <?php //Pjax::begin(['id' => $pjaxgridview_id, 'enablePushState' => false, 'clientOptions' => ['method' => 'POST']]); ?>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <?= GridView::widget([
            'id' => 'grid-view',
            'options' => ['class' => 'table-responsive'],
            'dataProvider' => $dataProvider,
            // 'filterModel' => $searchModel,
            'columns' => [
                [
                    'class' => 'yii\grid\ActionColumn', 
                    'template' => '{update} {delete}',
                    'visibleButtons' => [
                        'delete' => function ($model, $key, $index) {
                            return $model->deleted !== 1;
                        }
                    ],
                    'buttons' => [
                        'update' => function ($url, $model) use ($pjaxgridview_id) {
                            $url = ['routers/index', 'id'  =>$model->id];
                            return Html::a(
                                "<span class='glyphicon glyphicon-edit'></span>",
                                $url,
                                ['data-pjax' => '1']
                            );
                        },
                        'delete' => function ($url, $model) use ($pjaxgridview_id) {
                            $url = ['routers/ajax-delete', 'id'  =>$model->id];
                            return Html::a("<span class='glyphicon glyphicon-trash'></span>", '#', [
                                'class' => 'arr-img pull-left',
                                'title' => 'Click here to delete',
                                'onclick' => "
                                if (confirm('Are you sure you want to delete this record ?') == true) 
                                    {                            
                                        $.ajax({          
                                            type: 'POST',
                                            dataType: 'json',
                                            cache: false,
                                            url: '" . Yii::$app->urlManager->createUrl(['routers/ajax-delete', 'id' => $model->id]) . "',
                                            success: function(response) {
                                                if(response.status == 'success') {
                                                    alert(response.message);
                                                    $.pjax.reload({container: '#" . $pjaxgridview_id . "'});                                                
                                                } else {
                                                    alert(response.errors);
                                                }
                                                
                                            }
                                        });
                                    };
                                    return false;
                                "
                            ]);
                        },
                    ],
                ],
                ['class' => 'yii\grid\SerialColumn'],
                'id',
                'sap_id',
                'hostname',
                'loopback',
                'mac_address',
                
                [
                    'filter' => false,
                    'attribute' => 'deleted',
                    'format' => 'raw',
                    'value' => function ($model, $key, $index, $column) {                        
                        return ($model->deleted == 1) ? 'YES' : 'NO';
                    }
                ],
                'created_at',
                'updated_at',
                'created_by',
                'updated_by',

                
            ],
        ]); ?>

        <?php //Pjax::end(); ?>

    </div>
    </div>
</div
<?php Pjax::end(); ?>>

<script>
$(function() {
    $(document).on("submit", "form#form-routers", function(event) {
        event.preventDefault(); // stopping submitting
        var data = $(this).serializeArray();
        var url = $(this).attr('action');
        $.ajax({
            url: url,
            type: 'post',
            dataType: 'json',
            data: data
        })
        .done(function(response) {
            if (response.status == 'success') {
                alert(response.message);
                $.pjax.reload({container: '#router'});
            } else {
                alert(JSON.stringify(response.errors));
            }
        })
        .fail(function() {
            console.log("error");
        });
    
    });
});
</script>

views/routers/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Routers */

$this->title = 'Update Routers: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Routers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="routers-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/routers/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Routers */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Routers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="routers-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'sap_id',
            'hostname',
            'loopback',
            'mac_address',
            'created_at',
            'updated_at',
            'created_by',
            'updated_by',
        ],
    ]) ?>

</div>